### ISSUE TITLE
no log out

### ISSUE THREAD

**Issue by nekrochaa-n** [2018-PemrogramanWeb-D/tugas7-fp-tcourier#3]
tidak ada log-out button, jadi setelah memesan, tidak bisa log-out atau melakukan aktivitas lagi

**Comment by 051mym** [comment]
Pesanan anda harus diacc oleh kurir terlebih, dahulu baru bisa logout.
Jadi customer tidak bisa kabur saat kurir mengantar pesanan.
Jika sudah selesai maka anda bisa back to job kemudian anda bisa logout.
![jancuk](https://user-images.githubusercontent.com/42793951/50162200-501dc880-0310-11e9-80bb-691244531889.JPG)
