### ISSUE TITLE
Tidak ada require login

### ISSUE THREAD

**Issue by mmanurung** [2018-PemrogramanWeb-D/tugas7-fp-tcourier#4]
Saat buka halaman lain selain home, login, masih tetap bisa diakses/ tidak diarahkan ke halaman login

Saat saya login
![2018-12-19 1](https://user-images.githubusercontent.com/37216884/50198224-38305e00-037d-11e9-983e-25dbbc374550.png)

Saat saya tidak melalui proses login, saya tetap bisa mengakses halaman lainnya, misal saya langsung mau membuka job.php
![2018-12-19 2](https://user-images.githubusercontent.com/37216884/50198294-90fff680-037d-11e9-8176-71195272b106.png)
Tetapi, saat saya mengakses customer.php tampilan mjd spt ini
![2018-12-19 3](https://user-images.githubusercontent.com/37216884/50198311-aa08a780-037d-11e9-85ef-80a433142abd.png)

**Comment by Armunz** [comment]
![fix2](https://user-images.githubusercontent.com/36951196/50200341-1ee0df00-0388-11e9-89b9-e10e57694cfe.jpg)
![fix3](https://user-images.githubusercontent.com/36951196/50200342-1ee0df00-0388-11e9-8f1c-cd7d1c17d16a.jpg)
![fix](https://user-images.githubusercontent.com/36951196/50200343-1f797580-0388-11e9-91f1-1b9a20b0ad59.jpg)

Referensi: https://stackoverflow.com/questions/16735747/php-redirect-if-not-logged-in
